server:
  port: 9090
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travel?serverTimezone=GMT%2B8&characterEncoding=UTF-8
    username: root
    password: a111
mybatis:
  mapper-locations: mappings/*.xml
  type-aliases-package: com.qf.j1904.pojo

